name: samtl-website
static_sites:
- environment_slug: html
  github:
    branch: samtl-static-site
    deploy_on_push: true
    repo: BokuInc/samtl
  name: samtl-website
  catchall_document: index.html
  routes:
  - path: /
  headers:
  - key: X-Frame-Options
    value: DENY
  - key: X-Content-Type-Options
    value: nosniff
  - key: Strict-Transport-Security
    value: max-age=31536000; includeSubDomains
  - key: Referrer-Policy
    value: strict-origin-when-cross-origin
  - key: Permissions-Policy
    value: camera=(), microphone=(), geolocation=()
